### ISSUE TITLE
Add functionality to allow date & time picker to default to blank when adding a new marker.

### ISSUE THREAD

**Issue by DRD161** [marleymarl/geotime#11]
As of now when a user adds a marker to the map the same date and time information is in the modal. When a user clicks the Save Footprint button the input fields should be blank when they go to add a new marker.

<img width="841" alt="Screen Shot 2020-03-23 at 3 14 15 PM" src="https://user-images.githubusercontent.com/29187448/77354677-9d5dc680-6d19-11ea-9ce8-0c037090aa19.png">

**Comment by heldersepu** [comment]
whoops, I think I messed up a bit fixing #16 
my fix there was to set the default to current date... 
Do we really need to allow blanks?

**Comment by heldersepu** [comment]
If all we need is when the Modal launches for the Pickers to go back to defaults we just add:
`destroyOnClose={true}`
I still think the default value on date should be today, will add PR with destroyOnClose
