### ISSUE TITLE
Fix Layout of MapContainer (Map and Table) Using Ant Design Grid

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#28]
Currently within MapContainer.js the Map and Table children are divided using some MapContainer component styling. This should be changed to use a Grid Layout (Row + Col, Col) so that the Map and Table are each in their own column. Ant Design docs for Grid are here: https://ant.design/components/grid/ .

Should be something like (use the span values listed in example below): 
<>
<Row>
<Col span={15}>
<Map ... />
</Col>
<Col span ={9}>
<Table .../>
</Col>
</Row>
</>

**Comment by heldersepu** [comment]
I can take on this...

**Comment by marleymarl** [comment]
Awesome

**Comment by heldersepu** [comment]
After the change to grid I notice that the map loads with one size but as soon as we add a marker the map shrinks a little, look like actual data in the table makes is expand a bit...

**Comment by heldersepu** [comment]
fixed that last little issue
