### ISSUE TITLE
Reduce size of table

### ISSUE THREAD

**Issue by heldersepu** [marleymarl/geotime#29]
Currently the table is displaying the lat and lon with 14 digits after the dot:

![Screenshot from 2020-03-30 14-38-05](https://user-images.githubusercontent.com/545474/77949101-672dc300-7294-11ea-98b7-ff4c711b64e8.png)

That is an overkill, we can reduce to just 6 without any problems

![Screenshot from 2020-03-30 14-38-08](https://user-images.githubusercontent.com/545474/77949106-6a28b380-7294-11ea-8de5-059fcb3fc92a.png)

**Comment by heldersepu** [comment]
There is a good answer on SO that talks about this:
https://gis.stackexchange.com/a/8674

> The sixth decimal place is worth up to 0.11 m: you can use this for laying out structures in detail, for designing landscapes, building roads. It should be more than good enough for tracking movements of glaciers and rivers. This can be achieved by taking painstaking measures with GPS, such as differentially corrected GPS.

**Comment by marleymarl** [comment]
I won't know about that until I do the time-geo proximity matching code which I have spec'ed but not written yet. We can revisit after that. If it's about saving space in the table for display though, we could just have function to prep the data for the table by mapping each object in the footprints and reducing their decimal places by X amount. Even so, let's push that back a bit in priority.

**Comment by heldersepu** [comment]
> LOL looks like that's exactly what you did now that I reviewed the code. :)
Yep: `.toFixed(6)` easy fix
