### ISSUE TITLE
Create an UpFrontButtonForm That Sets A PatientID Using A UUID

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#32]
Create a new component like UpFrontForm (don't overwrite UFF) that instead of an input form has just a button 'Start Timeline' that when clicked sets the PatientID in the parent component (same function as with UFF) using an ID generated by the UUID library: https://www.npmjs.com/package/uuid.

**Comment by rtf-const** [comment]
Should is save last generated uuid locally and then reuse it if the same user use the component again?

**Comment by heldersepu** [comment]
> Should it save generated uuid locally and then reuse it if the same user uses the component again?

Probably no need to save it locally for reuse, I believe the end-users are probably going to be social workers entering new patients quite often

**Comment by heldersepu** [comment]
@rtf-const your work on PR #34 looks good...
but I think  we will also need a way to "search" for existing patients by ID

**Comment by heldersepu** [comment]
Should we look for a way to combine the `upFrontForm` and `upFrontButtonForm` into one?
something similar to the gmail sign-in:
![Screenshot from 2020-04-01 19-04-20](https://user-images.githubusercontent.com/545474/78194628-b0744300-744b-11ea-8b62-53680b92da64.png)

right from that one page we can: 
- input our info (retrieve existing)
- create new one (the UUID)

**Comment by marleymarl** [comment]
We definitely don't want to take email, so we wouldn't need that form, it should be just the button and unless we are integrating into someone else's system we don't want to allow retrieval of existing (as this requires us to store personal info). I'm just getting caught up on this thread, so will read above and comment.

**Comment by marleymarl** [comment]
I understand the thought process around letting a 'patient' come back and re-enter info but I think it's worth not having that ability in order to save ourselves from the minefield of storing that data locally or in our DB. We can change later but starting with the most privacy, least complex way to get timelines of historical footprints anonymously is the best to start with I think. As I said above this could be different for testing orgs and jurisdictions that import but if all we get is a list of footprints with timestamps (in a set representing one cases timeline) then this is way better than what is available now. Will there be some people who don't get it right and want to come back? Sure. But they just enter a new timeline for the footprints they forgot. The benefits we get by not asking / storing that info far outweigh any benefit we get by more fully stitching together full timelines of people who forgot one or two footprints.

**Comment by marleymarl** [comment]
Happy to be proven wrong through feedback of course. :) I feel strongly though that feedback so far has been most private / anonymous solution is best.

**Comment by marleymarl** [comment]
> Should it save generated uuid locally and then reuse it if the same user uses the component again?

No, I don't think it should. It should only save in state until the user hits 'Save and Exit' at which point it should reset the state to ''.
