### ISSUE TITLE
Functionality to Delete Footprints

### ISSUE THREAD

**Issue by V1shvesh** [marleymarl/geotime#33]

**Comment by heldersepu** [comment]
Any ideas how to approach this?
We could add a delete button to the Modal

**Comment by heldersepu** [comment]
Nice turn around @rtf-const !
Do we want to add way to delete items on the table too??

**Comment by heldersepu** [comment]
![Screenshot from 2020-04-01 16-38-04](https://user-images.githubusercontent.com/545474/78184313-42be1c00-7437-11ea-8ada-5842e71cf67a.png)
Maybe we should make the button just `Delete` so it fits better

**Comment by wakoong** [comment]
How about we add a delete icon (i.e. trash can, x button) on the far-right or far-left of the columns to prevent users from having to click the DatePicker? 
<img width="576" alt="Screen Shot 2020-04-01 at 1 56 25 PM" src="https://user-images.githubusercontent.com/14880130/78186104-04b5fd80-7421-11ea-8981-d771799a3ee3.png">

**Comment by heldersepu** [comment]
@wakoong that would be awesome! 
see if you can reuse the function that does the deletion
