### ISSUE TITLE
User should only be allowed to add current or past footprints

### ISSUE THREAD

**Issue by wakoong** [marleymarl/geotime#36]
Currently, users can add footprints on future dates. The app should prevent users from submitting footprints with future dates.

**Comment by heldersepu** [comment]
Should be an easy fix, there is a disabledDate prop:
https://stackblitz.com/edit/react-fcce79?file=index.js

**Comment by wakoong** [comment]
I made a pull request not knowing the issue was solved already. I closed the request but let me know if you want the request to be reopened. Thanks.

**Comment by heldersepu** [comment]
Just test the latest implementation see if you see any major issues as is

**Comment by wakoong** [comment]
Reopened the request. My code disables selecting future hours and minutes as well. Please take a look. Thanks!

**Comment by heldersepu** [comment]
@wakoong left you a comment on your PR...
you have a bug the disabling of hours and minutes is applying to yesterday and prior dates as well...
but limiting time is just not a big deal IMHO we can leave without that
