### ISSUE TITLE
Create a 'DataView' Component That Displays All Footprints in a Table

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#38]
This component should look like a stand-alone screen with a table on it (ideally filterable and/or sortable but not necessary for first commit). You can get all the footprints from the DB by making a GET request to https://cn1aotmhx0.execute-api.us-east-1.amazonaws.com/default/getfootprints. 

Would be good to also add a 'Download to CSV' button somewhere to download the complete table.

**Comment by heldersepu** [comment]
Is this to replace the existing table: 
https://github.com/marleymarl/geotime/blob/4f40c7c078bb7048692790d040cc0ea957acf8d5/src/MapContainer.js#L266-L272

**Comment by marleymarl** [comment]
No, this is a separate component. It will display as its own page (i.e. a page with a big table on it). Whereas the MapContainer Table is for display the footprints for the case/timeline that a user is currently working on, the DataView Table display all footprints from all cases/timelines in the DB. It's essentially the CSV view like the Korea/Taiwan/Israel dataset except available on our site instead of in Github (although I think we will publish a repo too - this table will update instantly whenever it's rendered whereas we might only update the repo daily). I think we will redirect the user to this data table view after they hit 'Save and Exit' in the Map View so that they can see that the records they just entered are now part of that global dataset.

**Comment by heldersepu** [comment]
Where is the code of that `getfootprints` ? looks like JSON forced as a string

**Comment by marleymarl** [comment]
https://github.com/marleymarl/geotimeline-backend/tree/master/get_footprints

**Comment by marleymarl** [comment]
I'll remove that stringify on the res and update.

**Comment by marleymarl** [comment]
Done.

**Comment by marleymarl** [comment]
I'm going to go ahead and take this one. :)
