### ISSUE TITLE
Place search feature required

### ISSUE THREAD

**Issue by KshitijMhatre** [marleymarl/geotime#40]
User might not always find visited places by scrolling or he may need to find landmarks with search.
This support is required in component. A search bar with autocomplete suggestions.

**Comment by marleymarl** [comment]
Hi @KshitijMhatre could you give a rough mock-up of where you will put it? I think it's a great idea by the way - I just want to make sure we have a thought of where it will fit.

**Comment by heldersepu** [comment]
@KshitijMhatre I added the input on the top of the map:

![Screenshot from 2020-04-04 22-55-32](https://user-images.githubusercontent.com/545474/78465748-79aa6100-76c7-11ea-8290-0410593d00c4.png)

Getting error:
 `This API project is not authorized to use this API. Places API error: ApiNotActivatedMapError` 
I think that is something @marleymarl has to enable for us.

but next steps will be to move the map to the location... see if you can get that to work

**Comment by heldersepu** [comment]
Looking good!
in my tests precise address are not showing in the search, for example this is the location of a hardware store near me and it does not auto-complete or gives us a result:
`12525 W Sunrise Blvd, Sunrise, FL 33323`
seems only cities are getting returns :thinking:

**Comment by KshitijMhatre** [comment]
So setting type list in types prop will restrict results to only those types. 
Passing empty list selects all type, while not sending this prop will select (cities) by default

**Comment by heldersepu** [comment]
Looks good
