### ISSUE TITLE
Upgrade DataView to using Antd Data Table or similar with filtering

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#52]
Right now DataView Table uses standard Ant Design Table component. See https://github.com/NewbeeFE/antd-data-table which seems like an upgrade and has some nice styling room for filters above table. 

Filters could be for data range to start (choose startDateTime and endDateTime) with some preset buttons/toggle links (last 14 days, last 5 days) and later location presets: within 5km / 20km etc of my location (may need to detect location and change km to miles for non-metric locations for that feature)

**Comment by marleymarl** [comment]
Also add 'Download to CSV' button above table to download the entire dataset.

**Comment by heldersepu** [comment]
Added sorting and filtering to the table using standard Table from antd:
https://ant.design/components/table/
![Screenshot from 2020-04-06 21-57-52](https://user-images.githubusercontent.com/545474/78621914-b7d38c00-7851-11ea-9e22-6da17f6b4f2d.png)


____
Tried getting the [antd-data-table](https://github.com/NewbeeFE/antd-data-table) to work but no luck...
also that module has not receive much activity recently:
https://github.com/NewbeeFE/antd-data-table/pulse/monthly

**Comment by marleymarl** [comment]
Nice filter and nice catch on the activity. :)

**Comment by heldersepu** [comment]
I wanna keep this open to implement the second part:
`location presets: within 5km / 20km etc of X location`

**Comment by heldersepu** [comment]
Added search button on the case_id

![Screenshot from 2020-04-11 17-46-20](https://user-images.githubusercontent.com/545474/79055722-39923380-7c1d-11ea-9ee4-6ef7dd6d529d.png)

**Comment by heldersepu** [comment]
Added search for the latitude and longitude:

![Screenshot from 2020-04-12 19-09-03](https://user-images.githubusercontent.com/545474/79082115-5b5cea80-7cf1-11ea-983e-aaae04c01e7f.png)

After much consideration and testing, I decided to go with a max-min search for each latitude and longitude, that way we give the end-user finer control and on our side, the calculations are simpler.
