### ISSUE TITLE
Add 'Save to CSV' button above the DataView Table

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#71]
Right now the 'Save to CSV' button is on MapContainer but it makes more sense now to have it on DataView. Add a 'Save to CSV' button above the DataView table. Refer to how that is working in MapContainer and recreate that functionality on DataView. 

If filters are applied to DataView (e.g. last 5 days only) then the CSV should only be what footprints are in that filtered array (i.e. not the full list of footprints that were originally returned from the API call). 

The 'Save to CSV' button should be aligned to the right and above the table.

**Comment by heldersepu** [comment]
Look like this is done! I just tested it works perfectly

**Comment by yukiyao119** [comment]
Oh ok! I Should've refreshed the page before self assigning. Thanks!
