### ISSUE TITLE
Add instruction box to fit above footprint table on MapContainer

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#75]
See the attached screenshot. Ideally the text in this instruction box (i.e. bullet points 1-3 etc.) would be collapsible, using https://ant.design/components/collapse/ with default state being 'active' (i.e. open).
![instructionboxabovefootprinttable](https://user-images.githubusercontent.com/35407723/79238727-c1ef1f00-7e3d-11ea-8df1-3267f7bb9c7e.png)

**Comment by heldersepu** [comment]
collapsible instruction box added ...

![Screenshot from 2020-04-14 21-49-26](https://user-images.githubusercontent.com/545474/79290337-d9f48c00-7e99-11ea-903f-4ad5775a7742.png)


looking at that image those two save buttons could use some styling ... should we make them the same size and color side by side
