### ISSUE TITLE
Create date range picker for 'selecting all footprints that match date and lat/lon range'

### ISSUE THREAD

**Issue by marleymarl** [marleymarl/geotime#78]
See attached screenshot. Create a date range picker that can fit inside the 'data' column of MapContainer and outputs a start date and end date onClick. 

[This should output two date/times (start date, end date) to be passed along with 'bounding box' coordinates (lat/lon points), determined by the Map (presumably by a calculation involving initialCenter and zoom level but that still needs to be spec'd, to an API to get back a set of Markers that match geo + date/time range. 

For this issue specifically though create the date range picker that outputs the date range (start, end) to console with an onClick function and we'll handle the geo coordinates grab and how to process the matching markers array that returns from API calls (including how we handle large arrays that need to be split into 'grouped markers') as separate issues.]
![daterangepicker](https://user-images.githubusercontent.com/35407723/79277883-a9502a80-7e78-11ea-82ef-ee85908be340.png)

**Comment by heldersepu** [comment]
DaterangeSearch added to Collapsible as key 3 panel:

https://github.com/marleymarl/geotime/blob/a5a001722b59687dfb3363590561f0f36446b728/src/MapContainer.js#L422-L424

![Screenshot from 2020-04-18 19-24-17](https://user-images.githubusercontent.com/545474/79673780-c2bfe200-81aa-11ea-9cd0-ef603080617b.png)
