### ISSUE TITLE
Improve mobile responsiveness of map component

### ISSUE THREAD

**Issue by DRD161** [marleymarl/geotime#9]
I would like to improve the mobile responsiveness of the component. Seeing as how mobile use is a huge portion of web traffic (especially in other countries) being able to report cases of COVID-19 on the go is crucial to the success of this project.

This would be a relatively simple fix that would have a huge impact on the project. Below is a screenshot of the current state of the project on mobile.

![IMG_B245ED9D9655-1](https://user-images.githubusercontent.com/29187448/77322014-738cab80-6ce9-11ea-8556-21eb4b0daf60.jpeg)

**Comment by DRD161** [comment]
Greg and I spoke today and decided to utilize a collapsible menu to house the information table. Starting at the tablet breakpoint the menu will default to open so that users have a clear indication as to what that table is for, what data has already been added, etc. Then they can close it as needed.

**Comment by heldersepu** [comment]
Was checking a bit on this and the page starts to show a horizontal scroll w/ anything less than 920px..
I'm hiding the information table(`.ant-col.data`) for anything less than that:
https://github.com/marleymarl/geotime/blob/51cd97a3167e018a72b4ebba181c09b62e10f93c/src/App.css#L44-L46

Next need to show a button to hide show the info table

**Comment by heldersepu** [comment]
Here is what I got so far:
![Screenshot from 2020-03-30 22-36-34](https://user-images.githubusercontent.com/545474/77981156-23a87880-72d7-11ea-911d-909bc24bba6d.png)


![Screenshot from 2020-03-30 22-37-00](https://user-images.githubusercontent.com/545474/77981145-1db29780-72d7-11ea-87f3-7ca75603d22c.png)

That new burger button on the bottom left shows when the screen is less than 920px

**Comment by heldersepu** [comment]
I was playing the table and I think we should consider combining lat/lon into one col to reduce teh size of the table...

see below:  
![Screenshot from 2020-03-31 11-57-29](https://user-images.githubusercontent.com/545474/78047870-e7acfc00-7346-11ea-8832-72e291f03a24.png)

**Comment by DRD161** [comment]
That makes sense. We may need to label them though so users know which is which. Also, it might be worth making the button larger so that it stands out more to users. We could also add text to the button to describe what it does.

**Comment by marleymarl** [comment]
This issue has been functionally solved with the change to the toggle button and the inclusion of the intro.js. I'm going to close this for now and we can open a new issue for any proposed changes based on user feedback.
